cargo-features = ["strip"]

[package]
name = "inexor-rgf-core-reactive"
description = "Inexor - Reactive Graph Flow - Core - Reactive"
version = "0.5.0"
authors = ["Andreas Schaeffer <hanack@nooblounge.net"]
edition = "2021"
license = "MIT"

[dependencies]
indradb-lib = "3"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
random-string = "1.0"
inexor-rgf-core-model = { git = "https://github.com/aschaeffer/inexor-rgf-core-model.git", branch = "bugfix/borrow_mut_error" }

[lib]
crate-type = ["lib"]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
# 12MB -> 7.8MB
lto = true
# 7.8MB -> 4.5MB
strip = "symbols"
# 4.5MB -> 3.7MB
# opt-level = "z"
